### ISSUE TITLE
Publish on pip

### ISSUE THREAD

**Issue by CosmicWebServices** [ilovecode1/pyfancy#31]
### What are you requesting?

We should have this published on pip so it can be more accessible.

**Comment by skistaddy** [comment]
duhhhhhh. :P

**Comment by CosmicWebServices** [comment]
@baranskistad do you know to publish on pip?

**Comment by skistaddy** [comment]
yah

**Comment by skistaddy** [comment]
create a pypi account then follow this article http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by CosmicWebServices** [comment]
Gotcha

**Comment by CosmicWebServices** [comment]
I was unable to publish on pip the other day... seemed to be a server issue with pip... will try again soon

**Comment by Kristinita** [comment]
+1

**Comment by Kristinita** [comment]
@CosmicWebServices, can you add pyfancy to PyPI? I want to add pyfancy as dependency of my package, but because pyfancy not on PyPI, I have problems.

### 1. Steps

Please, register on [**PyPI**](https://pypi.python.org/).

Install twine:

    pip install twine

Run this command in command line:

    python setup.py sdist && twine upload dist/*

pyfancy must add to PyPI.

### 2. Note

After last command Python adds to your local repository some folders and files. That not push them to GitHub, you can make `.gitignore` as in [**my Python repository**](https://github.com/Kristinita/Erichek/blob/master/.gitignore).

See also [**Python .gitignore boilerplate**](https://github.com/github/gitignore/blob/master/Python.gitignore) in official GitHub repository.

Thanks.

**Comment by CosmicWebServices** [comment]
@Kristinita Thanks so much for the instructions... I am going to do that right now :D

**Comment by CosmicWebServices** [comment]
@Kristinita Finally figured it out :D https://pypi.python.org/pypi/pyfancy/2.4.4

**Comment by Kristinita** [comment]
@CosmicWebServices , thanks! As you see, [**Markdown displayed incorrect**](https://pypi.python.org/pypi/pyfancy/2.4.4) in the page of your package on PyPI. I'm sorry for it.

Maybe, you make actions from 3.1.1 or 3.1.2 from my [**pull request**](https://github.com/ilovecode1/Pyfancy-2/pull/53)?

Thanks.
